name: Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        cd ./src/
        python -m pip install --upgrade -e .
        pytest --cov=./ --cov-report=xml
        cd ..
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./src/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./src/coverage.xml
        flags: unittests
        verbose: true
